version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb
  libro-service:
    build: ./libro-service
    ports:
      - "8081:8080"
    depends_on:
      - mongo
  autor-service:
    build: ./autor-service
    ports:
      - "8082:8080"
    depends_on:
      - mongo
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - libro-service
      - autor-service